// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: meter.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ManyMeterSimulator.KimbalSpecifics.Kmesh {

  /// <summary>Holder for reflection information generated from meter.proto</summary>
  public static partial class MeterReflection {

    #region Descriptor
    /// <summary>File descriptor for meter.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MeterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgttZXRlci5wcm90bxIFa21lc2gaDGNvbW1vbi5wcm90byJICgdHQlRQdXNo",
            "EhIKCmxhc3RfYmxvY2sYASACKAgSGAoQZ2J0X2Jsb2NrX251bWJlchgCIAIo",
            "DRIPCgdmcmFtZWlkGAMgAigNItoBCghQdXNoRGF0YRIUCgxtYWdpY19udW1i",
            "ZXIYASACKA0SEwoLbWFjX2FkZHJlc3MYAiACKA0SFAoMbWV0ZXJfbnVtYmVy",
            "GAMgAigJEiUKCXJlc3BfdHlwZRgEIAIoDjISLmttZXNoLlJlcXVlc3RUeXBl",
            "EhAKCGZyYW1lX2lkGAUgAigNEiYKCWZyYWdfaW5mbxgGIAEoCzITLmttZXNo",
            "LkZyYWdtZW50SW5mbxIPCgdwYXlsb2FkGAcgAigMEhsKA2didBgIIAEoCzIO",
            "LmttZXNoLkdCVFB1c2giVQoPUHVzaERhdGFNZXNzYWdlEiMKBmhlYWRlchgB",
            "IAIoCzITLmttZXNoLkNvbW1vbkhlYWRlchIdCgRkYXRhGAIgAigLMg8ua21l",
            "c2guUHVzaERhdGEiPwoLTm9kZVJlcXVlc3QSDwoHbm9kZV9pZBgBIAIoDRIf",
            "CgdyZXF1ZXN0GAIgAigLMg4ua21lc2guUmVxdWVzdCJWCgxOb2RlUmVzcG9u",
            "c2USIwoGaGVhZGVyGAEgAigLMhMua21lc2guQ29tbW9uSGVhZGVyEiEKCHJl",
            "c3BvbnNlGAIgAigLMg8ua21lc2guUmVzcG9uc2U="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ManyMeterSimulator.KimbalSpecifics.Kmesh.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ManyMeterSimulator.KimbalSpecifics.Kmesh.GBTPush), global::ManyMeterSimulator.KimbalSpecifics.Kmesh.GBTPush.Parser, new[]{ "LastBlock", "GbtBlockNumber", "Frameid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ManyMeterSimulator.KimbalSpecifics.Kmesh.PushData), global::ManyMeterSimulator.KimbalSpecifics.Kmesh.PushData.Parser, new[]{ "MagicNumber", "MacAddress", "MeterNumber", "RespType", "FrameId", "FragInfo", "Payload", "Gbt" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ManyMeterSimulator.KimbalSpecifics.Kmesh.PushDataMessage), global::ManyMeterSimulator.KimbalSpecifics.Kmesh.PushDataMessage.Parser, new[]{ "Header", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ManyMeterSimulator.KimbalSpecifics.Kmesh.NodeRequest), global::ManyMeterSimulator.KimbalSpecifics.Kmesh.NodeRequest.Parser, new[]{ "NodeId", "Request" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ManyMeterSimulator.KimbalSpecifics.Kmesh.NodeResponse), global::ManyMeterSimulator.KimbalSpecifics.Kmesh.NodeResponse.Parser, new[]{ "Header", "Response" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GBTPush : pb::IMessage<GBTPush>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GBTPush> _parser = new pb::MessageParser<GBTPush>(() => new GBTPush());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GBTPush> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ManyMeterSimulator.KimbalSpecifics.Kmesh.MeterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GBTPush() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GBTPush(GBTPush other) : this() {
      _hasBits0 = other._hasBits0;
      lastBlock_ = other.lastBlock_;
      gbtBlockNumber_ = other.gbtBlockNumber_;
      frameid_ = other.frameid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GBTPush Clone() {
      return new GBTPush(this);
    }

    /// <summary>Field number for the "last_block" field.</summary>
    public const int LastBlockFieldNumber = 1;
    private readonly static bool LastBlockDefaultValue = false;

    private bool lastBlock_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool LastBlock {
      get { if ((_hasBits0 & 1) != 0) { return lastBlock_; } else { return LastBlockDefaultValue; } }
      set {
        _hasBits0 |= 1;
        lastBlock_ = value;
      }
    }
    /// <summary>Gets whether the "last_block" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLastBlock {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "last_block" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLastBlock() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "gbt_block_number" field.</summary>
    public const int GbtBlockNumberFieldNumber = 2;
    private readonly static uint GbtBlockNumberDefaultValue = 0;

    private uint gbtBlockNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GbtBlockNumber {
      get { if ((_hasBits0 & 2) != 0) { return gbtBlockNumber_; } else { return GbtBlockNumberDefaultValue; } }
      set {
        _hasBits0 |= 2;
        gbtBlockNumber_ = value;
      }
    }
    /// <summary>Gets whether the "gbt_block_number" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGbtBlockNumber {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "gbt_block_number" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGbtBlockNumber() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "frameid" field.</summary>
    public const int FrameidFieldNumber = 3;
    private readonly static uint FrameidDefaultValue = 0;

    private uint frameid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Frameid {
      get { if ((_hasBits0 & 4) != 0) { return frameid_; } else { return FrameidDefaultValue; } }
      set {
        _hasBits0 |= 4;
        frameid_ = value;
      }
    }
    /// <summary>Gets whether the "frameid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFrameid {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "frameid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFrameid() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GBTPush);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GBTPush other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LastBlock != other.LastBlock) return false;
      if (GbtBlockNumber != other.GbtBlockNumber) return false;
      if (Frameid != other.Frameid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasLastBlock) hash ^= LastBlock.GetHashCode();
      if (HasGbtBlockNumber) hash ^= GbtBlockNumber.GetHashCode();
      if (HasFrameid) hash ^= Frameid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasLastBlock) {
        output.WriteRawTag(8);
        output.WriteBool(LastBlock);
      }
      if (HasGbtBlockNumber) {
        output.WriteRawTag(16);
        output.WriteUInt32(GbtBlockNumber);
      }
      if (HasFrameid) {
        output.WriteRawTag(24);
        output.WriteUInt32(Frameid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasLastBlock) {
        output.WriteRawTag(8);
        output.WriteBool(LastBlock);
      }
      if (HasGbtBlockNumber) {
        output.WriteRawTag(16);
        output.WriteUInt32(GbtBlockNumber);
      }
      if (HasFrameid) {
        output.WriteRawTag(24);
        output.WriteUInt32(Frameid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasLastBlock) {
        size += 1 + 1;
      }
      if (HasGbtBlockNumber) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GbtBlockNumber);
      }
      if (HasFrameid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Frameid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GBTPush other) {
      if (other == null) {
        return;
      }
      if (other.HasLastBlock) {
        LastBlock = other.LastBlock;
      }
      if (other.HasGbtBlockNumber) {
        GbtBlockNumber = other.GbtBlockNumber;
      }
      if (other.HasFrameid) {
        Frameid = other.Frameid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LastBlock = input.ReadBool();
            break;
          }
          case 16: {
            GbtBlockNumber = input.ReadUInt32();
            break;
          }
          case 24: {
            Frameid = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LastBlock = input.ReadBool();
            break;
          }
          case 16: {
            GbtBlockNumber = input.ReadUInt32();
            break;
          }
          case 24: {
            Frameid = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PushData : pb::IMessage<PushData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PushData> _parser = new pb::MessageParser<PushData>(() => new PushData());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PushData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ManyMeterSimulator.KimbalSpecifics.Kmesh.MeterReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PushData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PushData(PushData other) : this() {
      _hasBits0 = other._hasBits0;
      magicNumber_ = other.magicNumber_;
      macAddress_ = other.macAddress_;
      meterNumber_ = other.meterNumber_;
      respType_ = other.respType_;
      frameId_ = other.frameId_;
      fragInfo_ = other.fragInfo_ != null ? other.fragInfo_.Clone() : null;
      payload_ = other.payload_;
      gbt_ = other.gbt_ != null ? other.gbt_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PushData Clone() {
      return new PushData(this);
    }

    /// <summary>Field number for the "magic_number" field.</summary>
    public const int MagicNumberFieldNumber = 1;
    private readonly static uint MagicNumberDefaultValue = 0;

    private uint magicNumber_;
    /// <summary>
    ///This should be optional
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MagicNumber {
      get { if ((_hasBits0 & 1) != 0) { return magicNumber_; } else { return MagicNumberDefaultValue; } }
      set {
        _hasBits0 |= 1;
        magicNumber_ = value;
      }
    }
    /// <summary>Gets whether the "magic_number" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMagicNumber {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "magic_number" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMagicNumber() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "mac_address" field.</summary>
    public const int MacAddressFieldNumber = 2;
    private readonly static uint MacAddressDefaultValue = 0;

    private uint macAddress_;
    /// <summary>
    ///This should be optional
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MacAddress {
      get { if ((_hasBits0 & 2) != 0) { return macAddress_; } else { return MacAddressDefaultValue; } }
      set {
        _hasBits0 |= 2;
        macAddress_ = value;
      }
    }
    /// <summary>Gets whether the "mac_address" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMacAddress {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "mac_address" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMacAddress() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "meter_number" field.</summary>
    public const int MeterNumberFieldNumber = 3;
    private readonly static string MeterNumberDefaultValue = "";

    private string meterNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MeterNumber {
      get { return meterNumber_ ?? MeterNumberDefaultValue; }
      set {
        meterNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "meter_number" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMeterNumber {
      get { return meterNumber_ != null; }
    }
    /// <summary>Clears the value of the "meter_number" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMeterNumber() {
      meterNumber_ = null;
    }

    /// <summary>Field number for the "resp_type" field.</summary>
    public const int RespTypeFieldNumber = 4;
    private readonly static global::ManyMeterSimulator.KimbalSpecifics.Kmesh.RequestType RespTypeDefaultValue = global::ManyMeterSimulator.KimbalSpecifics.Kmesh.RequestType.KapUnknownData;

    private global::ManyMeterSimulator.KimbalSpecifics.Kmesh.RequestType respType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManyMeterSimulator.KimbalSpecifics.Kmesh.RequestType RespType {
      get { if ((_hasBits0 & 4) != 0) { return respType_; } else { return RespTypeDefaultValue; } }
      set {
        _hasBits0 |= 4;
        respType_ = value;
      }
    }
    /// <summary>Gets whether the "resp_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRespType {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "resp_type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRespType() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "frame_id" field.</summary>
    public const int FrameIdFieldNumber = 5;
    private readonly static uint FrameIdDefaultValue = 0;

    private uint frameId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FrameId {
      get { if ((_hasBits0 & 8) != 0) { return frameId_; } else { return FrameIdDefaultValue; } }
      set {
        _hasBits0 |= 8;
        frameId_ = value;
      }
    }
    /// <summary>Gets whether the "frame_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFrameId {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "frame_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFrameId() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "frag_info" field.</summary>
    public const int FragInfoFieldNumber = 6;
    private global::ManyMeterSimulator.KimbalSpecifics.Kmesh.FragmentInfo fragInfo_;
    /// <summary>
    ///multi-fragment
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManyMeterSimulator.KimbalSpecifics.Kmesh.FragmentInfo FragInfo {
      get { return fragInfo_; }
      set {
        fragInfo_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 7;
    private readonly static pb::ByteString PayloadDefaultValue = pb::ByteString.Empty;

    private pb::ByteString payload_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Payload {
      get { return payload_ ?? PayloadDefaultValue; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "payload" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPayload {
      get { return payload_ != null; }
    }
    /// <summary>Clears the value of the "payload" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payload_ = null;
    }

    /// <summary>Field number for the "gbt" field.</summary>
    public const int GbtFieldNumber = 8;
    private global::ManyMeterSimulator.KimbalSpecifics.Kmesh.GBTPush gbt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManyMeterSimulator.KimbalSpecifics.Kmesh.GBTPush Gbt {
      get { return gbt_; }
      set {
        gbt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PushData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PushData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MagicNumber != other.MagicNumber) return false;
      if (MacAddress != other.MacAddress) return false;
      if (MeterNumber != other.MeterNumber) return false;
      if (RespType != other.RespType) return false;
      if (FrameId != other.FrameId) return false;
      if (!object.Equals(FragInfo, other.FragInfo)) return false;
      if (Payload != other.Payload) return false;
      if (!object.Equals(Gbt, other.Gbt)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasMagicNumber) hash ^= MagicNumber.GetHashCode();
      if (HasMacAddress) hash ^= MacAddress.GetHashCode();
      if (HasMeterNumber) hash ^= MeterNumber.GetHashCode();
      if (HasRespType) hash ^= RespType.GetHashCode();
      if (HasFrameId) hash ^= FrameId.GetHashCode();
      if (fragInfo_ != null) hash ^= FragInfo.GetHashCode();
      if (HasPayload) hash ^= Payload.GetHashCode();
      if (gbt_ != null) hash ^= Gbt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasMagicNumber) {
        output.WriteRawTag(8);
        output.WriteUInt32(MagicNumber);
      }
      if (HasMacAddress) {
        output.WriteRawTag(16);
        output.WriteUInt32(MacAddress);
      }
      if (HasMeterNumber) {
        output.WriteRawTag(26);
        output.WriteString(MeterNumber);
      }
      if (HasRespType) {
        output.WriteRawTag(32);
        output.WriteEnum((int) RespType);
      }
      if (HasFrameId) {
        output.WriteRawTag(40);
        output.WriteUInt32(FrameId);
      }
      if (fragInfo_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(FragInfo);
      }
      if (HasPayload) {
        output.WriteRawTag(58);
        output.WriteBytes(Payload);
      }
      if (gbt_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Gbt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasMagicNumber) {
        output.WriteRawTag(8);
        output.WriteUInt32(MagicNumber);
      }
      if (HasMacAddress) {
        output.WriteRawTag(16);
        output.WriteUInt32(MacAddress);
      }
      if (HasMeterNumber) {
        output.WriteRawTag(26);
        output.WriteString(MeterNumber);
      }
      if (HasRespType) {
        output.WriteRawTag(32);
        output.WriteEnum((int) RespType);
      }
      if (HasFrameId) {
        output.WriteRawTag(40);
        output.WriteUInt32(FrameId);
      }
      if (fragInfo_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(FragInfo);
      }
      if (HasPayload) {
        output.WriteRawTag(58);
        output.WriteBytes(Payload);
      }
      if (gbt_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Gbt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasMagicNumber) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MagicNumber);
      }
      if (HasMacAddress) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MacAddress);
      }
      if (HasMeterNumber) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MeterNumber);
      }
      if (HasRespType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RespType);
      }
      if (HasFrameId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FrameId);
      }
      if (fragInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FragInfo);
      }
      if (HasPayload) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
      }
      if (gbt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Gbt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PushData other) {
      if (other == null) {
        return;
      }
      if (other.HasMagicNumber) {
        MagicNumber = other.MagicNumber;
      }
      if (other.HasMacAddress) {
        MacAddress = other.MacAddress;
      }
      if (other.HasMeterNumber) {
        MeterNumber = other.MeterNumber;
      }
      if (other.HasRespType) {
        RespType = other.RespType;
      }
      if (other.HasFrameId) {
        FrameId = other.FrameId;
      }
      if (other.fragInfo_ != null) {
        if (fragInfo_ == null) {
          FragInfo = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.FragmentInfo();
        }
        FragInfo.MergeFrom(other.FragInfo);
      }
      if (other.HasPayload) {
        Payload = other.Payload;
      }
      if (other.gbt_ != null) {
        if (gbt_ == null) {
          Gbt = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.GBTPush();
        }
        Gbt.MergeFrom(other.Gbt);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MagicNumber = input.ReadUInt32();
            break;
          }
          case 16: {
            MacAddress = input.ReadUInt32();
            break;
          }
          case 26: {
            MeterNumber = input.ReadString();
            break;
          }
          case 32: {
            RespType = (global::ManyMeterSimulator.KimbalSpecifics.Kmesh.RequestType) input.ReadEnum();
            break;
          }
          case 40: {
            FrameId = input.ReadUInt32();
            break;
          }
          case 50: {
            if (fragInfo_ == null) {
              FragInfo = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.FragmentInfo();
            }
            input.ReadMessage(FragInfo);
            break;
          }
          case 58: {
            Payload = input.ReadBytes();
            break;
          }
          case 66: {
            if (gbt_ == null) {
              Gbt = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.GBTPush();
            }
            input.ReadMessage(Gbt);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MagicNumber = input.ReadUInt32();
            break;
          }
          case 16: {
            MacAddress = input.ReadUInt32();
            break;
          }
          case 26: {
            MeterNumber = input.ReadString();
            break;
          }
          case 32: {
            RespType = (global::ManyMeterSimulator.KimbalSpecifics.Kmesh.RequestType) input.ReadEnum();
            break;
          }
          case 40: {
            FrameId = input.ReadUInt32();
            break;
          }
          case 50: {
            if (fragInfo_ == null) {
              FragInfo = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.FragmentInfo();
            }
            input.ReadMessage(FragInfo);
            break;
          }
          case 58: {
            Payload = input.ReadBytes();
            break;
          }
          case 66: {
            if (gbt_ == null) {
              Gbt = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.GBTPush();
            }
            input.ReadMessage(Gbt);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PushDataMessage : pb::IMessage<PushDataMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PushDataMessage> _parser = new pb::MessageParser<PushDataMessage>(() => new PushDataMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PushDataMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ManyMeterSimulator.KimbalSpecifics.Kmesh.MeterReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PushDataMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PushDataMessage(PushDataMessage other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PushDataMessage Clone() {
      return new PushDataMessage(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::ManyMeterSimulator.KimbalSpecifics.Kmesh.CommonHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManyMeterSimulator.KimbalSpecifics.Kmesh.CommonHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private global::ManyMeterSimulator.KimbalSpecifics.Kmesh.PushData data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManyMeterSimulator.KimbalSpecifics.Kmesh.PushData Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PushDataMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PushDataMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PushDataMessage other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.CommonHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.PushData();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.CommonHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            if (data_ == null) {
              Data = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.PushData();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.CommonHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            if (data_ == null) {
              Data = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.PushData();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class NodeRequest : pb::IMessage<NodeRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NodeRequest> _parser = new pb::MessageParser<NodeRequest>(() => new NodeRequest());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NodeRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ManyMeterSimulator.KimbalSpecifics.Kmesh.MeterReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NodeRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NodeRequest(NodeRequest other) : this() {
      _hasBits0 = other._hasBits0;
      nodeId_ = other.nodeId_;
      request_ = other.request_ != null ? other.request_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NodeRequest Clone() {
      return new NodeRequest(this);
    }

    /// <summary>Field number for the "node_id" field.</summary>
    public const int NodeIdFieldNumber = 1;
    private readonly static uint NodeIdDefaultValue = 0;

    private uint nodeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NodeId {
      get { if ((_hasBits0 & 1) != 0) { return nodeId_; } else { return NodeIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        nodeId_ = value;
      }
    }
    /// <summary>Gets whether the "node_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNodeId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "node_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNodeId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 2;
    private global::ManyMeterSimulator.KimbalSpecifics.Kmesh.Request request_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManyMeterSimulator.KimbalSpecifics.Kmesh.Request Request {
      get { return request_; }
      set {
        request_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NodeRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NodeRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NodeId != other.NodeId) return false;
      if (!object.Equals(Request, other.Request)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasNodeId) hash ^= NodeId.GetHashCode();
      if (request_ != null) hash ^= Request.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasNodeId) {
        output.WriteRawTag(8);
        output.WriteUInt32(NodeId);
      }
      if (request_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Request);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasNodeId) {
        output.WriteRawTag(8);
        output.WriteUInt32(NodeId);
      }
      if (request_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Request);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasNodeId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NodeId);
      }
      if (request_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NodeRequest other) {
      if (other == null) {
        return;
      }
      if (other.HasNodeId) {
        NodeId = other.NodeId;
      }
      if (other.request_ != null) {
        if (request_ == null) {
          Request = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.Request();
        }
        Request.MergeFrom(other.Request);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            NodeId = input.ReadUInt32();
            break;
          }
          case 18: {
            if (request_ == null) {
              Request = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.Request();
            }
            input.ReadMessage(Request);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            NodeId = input.ReadUInt32();
            break;
          }
          case 18: {
            if (request_ == null) {
              Request = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.Request();
            }
            input.ReadMessage(Request);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class NodeResponse : pb::IMessage<NodeResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NodeResponse> _parser = new pb::MessageParser<NodeResponse>(() => new NodeResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NodeResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ManyMeterSimulator.KimbalSpecifics.Kmesh.MeterReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NodeResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NodeResponse(NodeResponse other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      response_ = other.response_ != null ? other.response_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NodeResponse Clone() {
      return new NodeResponse(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::ManyMeterSimulator.KimbalSpecifics.Kmesh.CommonHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManyMeterSimulator.KimbalSpecifics.Kmesh.CommonHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 2;
    private global::ManyMeterSimulator.KimbalSpecifics.Kmesh.Response response_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ManyMeterSimulator.KimbalSpecifics.Kmesh.Response Response {
      get { return response_; }
      set {
        response_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NodeResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NodeResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (!object.Equals(Response, other.Response)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (response_ != null) hash ^= Response.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (response_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Response);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (response_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Response);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (response_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NodeResponse other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.CommonHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.response_ != null) {
        if (response_ == null) {
          Response = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.Response();
        }
        Response.MergeFrom(other.Response);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.CommonHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            if (response_ == null) {
              Response = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.Response();
            }
            input.ReadMessage(Response);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.CommonHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            if (response_ == null) {
              Response = new global::ManyMeterSimulator.KimbalSpecifics.Kmesh.Response();
            }
            input.ReadMessage(Response);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
