// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace ManyMeterSimulator.KimbalSpecifics.Wirepas
{

    [global::ProtoBuf.ProtoContract()]
    public partial class NanoPBOptions //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int max_size
        {
            get { return __pbn__max_size.GetValueOrDefault(); }
            set { __pbn__max_size = value; }
        }
        public bool ShouldSerializemax_size() => __pbn__max_size != null;
        public void Resetmax_size() => __pbn__max_size = null;
        private int? __pbn__max_size;

        [global::ProtoBuf.ProtoMember(14)]
        public int max_length
        {
            get { return __pbn__max_length.GetValueOrDefault(); }
            set { __pbn__max_length = value; }
        }
        public bool ShouldSerializemax_length() => __pbn__max_length != null;
        public void Resetmax_length() => __pbn__max_length = null;
        private int? __pbn__max_length;

        [global::ProtoBuf.ProtoMember(2)]
        public int max_count
        {
            get { return __pbn__max_count.GetValueOrDefault(); }
            set { __pbn__max_count = value; }
        }
        public bool ShouldSerializemax_count() => __pbn__max_count != null;
        public void Resetmax_count() => __pbn__max_count = null;
        private int? __pbn__max_count;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(IntSize.IsDefault)]
        public IntSize int_size
        {
            get { return __pbn__int_size ?? IntSize.IsDefault; }
            set { __pbn__int_size = value; }
        }
        public bool ShouldSerializeint_size() => __pbn__int_size != null;
        public void Resetint_size() => __pbn__int_size = null;
        private IntSize? __pbn__int_size;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(FieldType.FtDefault)]
        public FieldType type
        {
            get { return __pbn__type ?? FieldType.FtDefault; }
            set { __pbn__type = value; }
        }
        public bool ShouldSerializetype() => __pbn__type != null;
        public void Resettype() => __pbn__type = null;
        private FieldType? __pbn__type;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool long_names
        {
            get { return __pbn__long_names ?? true; }
            set { __pbn__long_names = value; }
        }
        public bool ShouldSerializelong_names() => __pbn__long_names != null;
        public void Resetlong_names() => __pbn__long_names = null;
        private bool? __pbn__long_names;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool packed_struct
        {
            get { return __pbn__packed_struct ?? false; }
            set { __pbn__packed_struct = value; }
        }
        public bool ShouldSerializepacked_struct() => __pbn__packed_struct != null;
        public void Resetpacked_struct() => __pbn__packed_struct = null;
        private bool? __pbn__packed_struct;

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool packed_enum
        {
            get { return __pbn__packed_enum ?? false; }
            set { __pbn__packed_enum = value; }
        }
        public bool ShouldSerializepacked_enum() => __pbn__packed_enum != null;
        public void Resetpacked_enum() => __pbn__packed_enum = null;
        private bool? __pbn__packed_enum;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool skip_message
        {
            get { return __pbn__skip_message ?? false; }
            set { __pbn__skip_message = value; }
        }
        public bool ShouldSerializeskip_message() => __pbn__skip_message != null;
        public void Resetskip_message() => __pbn__skip_message = null;
        private bool? __pbn__skip_message;

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool no_unions
        {
            get { return __pbn__no_unions ?? false; }
            set { __pbn__no_unions = value; }
        }
        public bool ShouldSerializeno_unions() => __pbn__no_unions != null;
        public void Resetno_unions() => __pbn__no_unions = null;
        private bool? __pbn__no_unions;

        [global::ProtoBuf.ProtoMember(9)]
        public uint msgid
        {
            get { return __pbn__msgid.GetValueOrDefault(); }
            set { __pbn__msgid = value; }
        }
        public bool ShouldSerializemsgid() => __pbn__msgid != null;
        public void Resetmsgid() => __pbn__msgid = null;
        private uint? __pbn__msgid;

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool anonymous_oneof
        {
            get { return __pbn__anonymous_oneof ?? false; }
            set { __pbn__anonymous_oneof = value; }
        }
        public bool ShouldSerializeanonymous_oneof() => __pbn__anonymous_oneof != null;
        public void Resetanonymous_oneof() => __pbn__anonymous_oneof = null;
        private bool? __pbn__anonymous_oneof;

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool proto3
        {
            get { return __pbn__proto3 ?? false; }
            set { __pbn__proto3 = value; }
        }
        public bool ShouldSerializeproto3() => __pbn__proto3 != null;
        public void Resetproto3() => __pbn__proto3 = null;
        private bool? __pbn__proto3;

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool enum_to_string
        {
            get { return __pbn__enum_to_string ?? false; }
            set { __pbn__enum_to_string = value; }
        }
        public bool ShouldSerializeenum_to_string() => __pbn__enum_to_string != null;
        public void Resetenum_to_string() => __pbn__enum_to_string = null;
        private bool? __pbn__enum_to_string;

        [global::ProtoBuf.ProtoMember(15)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool fixed_length
        {
            get { return __pbn__fixed_length ?? false; }
            set { __pbn__fixed_length = value; }
        }
        public bool ShouldSerializefixed_length() => __pbn__fixed_length != null;
        public void Resetfixed_length() => __pbn__fixed_length = null;
        private bool? __pbn__fixed_length;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestHeader //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong req_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string sink_id
        {
            get { return __pbn__sink_id ?? ""; }
            set { __pbn__sink_id = value; }
        }
        public bool ShouldSerializesink_id() => __pbn__sink_id != null;
        public void Resetsink_id() => __pbn__sink_id = null;
        private string __pbn__sink_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseHeader //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong req_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string gw_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string sink_id
        {
            get { return __pbn__sink_id ?? ""; }
            set { __pbn__sink_id = value; }
        }
        public bool ShouldSerializesink_id() => __pbn__sink_id != null;
        public void Resetsink_id() => __pbn__sink_id = null;
        private string __pbn__sink_id;

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public ErrorCode res { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EventHeader //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string gw_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string sink_id
        {
            get { return __pbn__sink_id ?? ""; }
            set { __pbn__sink_id = value; }
        }
        public bool ShouldSerializesink_id() => __pbn__sink_id != null;
        public void Resetsink_id() => __pbn__sink_id = null;
        private string __pbn__sink_id;

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public ulong event_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FirmwareVersion //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint major { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint minor { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public uint maint { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public uint dev { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScratchpadInfo //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint len { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint crc { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public uint seq { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetScratchpadStatusReq //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public RequestHeader header { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetScratchpadStatusResp //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ResponseHeader header { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ScratchpadInfo stored_scratchpad { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(ScratchpadStatus.Success)]
        public ScratchpadStatus stored_status
        {
            get { return __pbn__stored_status ?? ScratchpadStatus.Success; }
            set { __pbn__stored_status = value; }
        }
        public bool ShouldSerializestored_status() => __pbn__stored_status != null;
        public void Resetstored_status() => __pbn__stored_status = null;
        private ScratchpadStatus? __pbn__stored_status;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(ScratchpadType.Blank)]
        public ScratchpadType stored_type
        {
            get { return __pbn__stored_type ?? ScratchpadType.Blank; }
            set { __pbn__stored_type = value; }
        }
        public bool ShouldSerializestored_type() => __pbn__stored_type != null;
        public void Resetstored_type() => __pbn__stored_type = null;
        private ScratchpadType? __pbn__stored_type;

        [global::ProtoBuf.ProtoMember(5)]
        public ScratchpadInfo processed_scratchpad { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint firmware_area_id
        {
            get { return __pbn__firmware_area_id.GetValueOrDefault(); }
            set { __pbn__firmware_area_id = value; }
        }
        public bool ShouldSerializefirmware_area_id() => __pbn__firmware_area_id != null;
        public void Resetfirmware_area_id() => __pbn__firmware_area_id = null;
        private uint? __pbn__firmware_area_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UploadScratchpadReq //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public RequestHeader header { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint seq { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public byte[] scratchpad
        {
            get { return __pbn__scratchpad; }
            set { __pbn__scratchpad = value; }
        }
        public bool ShouldSerializescratchpad() => __pbn__scratchpad != null;
        public void Resetscratchpad() => __pbn__scratchpad = null;
        private byte[] __pbn__scratchpad;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UploadScratchpadResp //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ResponseHeader header { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProcessScratchpadReq //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public RequestHeader header { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProcessScratchpadResp //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ResponseHeader header { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendPacketReq //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public RequestHeader header { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint destination_address { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public uint source_endpoint { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public uint destination_endpoint { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public uint qos { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public byte[] payload { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public uint initial_delay_ms
        {
            get { return __pbn__initial_delay_ms.GetValueOrDefault(); }
            set { __pbn__initial_delay_ms = value; }
        }
        public bool ShouldSerializeinitial_delay_ms() => __pbn__initial_delay_ms != null;
        public void Resetinitial_delay_ms() => __pbn__initial_delay_ms = null;
        private uint? __pbn__initial_delay_ms;

        [global::ProtoBuf.ProtoMember(8)]
        public bool is_unack_csma_ca
        {
            get { return __pbn__is_unack_csma_ca.GetValueOrDefault(); }
            set { __pbn__is_unack_csma_ca = value; }
        }
        public bool ShouldSerializeis_unack_csma_ca() => __pbn__is_unack_csma_ca != null;
        public void Resetis_unack_csma_ca() => __pbn__is_unack_csma_ca = null;
        private bool? __pbn__is_unack_csma_ca;

        [global::ProtoBuf.ProtoMember(9)]
        public uint hop_limit
        {
            get { return __pbn__hop_limit.GetValueOrDefault(); }
            set { __pbn__hop_limit = value; }
        }
        public bool ShouldSerializehop_limit() => __pbn__hop_limit != null;
        public void Resethop_limit() => __pbn__hop_limit = null;
        private uint? __pbn__hop_limit;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendPacketResp //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ResponseHeader header { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PacketReceivedEvent //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public EventHeader header { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public long source_address { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public long destination_address { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public uint source_endpoint { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public uint destination_endpoint { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public uint travel_time_ms { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public ulong rx_time_ms_epoch { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public uint qos { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public byte[] payload
        {
            get;// { return __pbn__payload; }
            set;// { __pbn__payload = value; }
        }
        //public bool ShouldSerializepayload() => __pbn__payload != null;
        //public void Resetpayload() => __pbn__payload = null;
        //private byte[] __pbn__payload;

        [global::ProtoBuf.ProtoMember(10)]
        public uint payload_size
        {
            get;// { return __pbn__payload_size.GetValueOrDefault(); }
            set;// { __pbn__payload_size = value; }
        }
        //public bool ShouldSerializepayload_size() => __pbn__payload_size != null;
        //public void Resetpayload_size() => __pbn__payload_size = null;
        //private uint? __pbn__payload_size;

        [global::ProtoBuf.ProtoMember(11)]
        public uint hop_count
        {
            get;// { return __pbn__hop_count.GetValueOrDefault(); }
            set; // { __pbn__hop_count = value; }
        }
        //public bool ShouldSerializehop_count() => __pbn__hop_count != null;
        //public void Resethop_count() => __pbn__hop_count = null;
        //private uint? __pbn__hop_count;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NodeRole //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public BaseRole role { get; set; } = BaseRole.Sink;

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<RoleFlags> flags { get; } = new global::System.Collections.Generic.List<RoleFlags>();

        [global::ProtoBuf.ProtoContract()]
        public enum BaseRole
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SINK")]
            Sink = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ROUTER")]
            Router = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"NON_ROUTER")]
            NonRouter = 3,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum RoleFlags
        {
            [global::ProtoBuf.ProtoEnum(Name = @"LOW_LATENCY")]
            LowLatency = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"AUTOROLE")]
            Autorole = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccessCycleRange //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint min_ms { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint max_ms { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChannelRange //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint min_channel { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint max_channel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppConfigData //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint diag_interval_s { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public byte[] app_config_data { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public uint seq { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NetworkKeys //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public byte[] cipher { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public byte[] authentication { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SinkReadConfig //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string sink_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public NodeRole node_role { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint node_address
        {
            get { return __pbn__node_address.GetValueOrDefault(); }
            set { __pbn__node_address = value; }
        }
        public bool ShouldSerializenode_address() => __pbn__node_address != null;
        public void Resetnode_address() => __pbn__node_address = null;
        private uint? __pbn__node_address;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong network_address
        {
            get { return __pbn__network_address.GetValueOrDefault(); }
            set { __pbn__network_address = value; }
        }
        public bool ShouldSerializenetwork_address() => __pbn__network_address != null;
        public void Resetnetwork_address() => __pbn__network_address = null;
        private ulong? __pbn__network_address;

        [global::ProtoBuf.ProtoMember(5)]
        public uint network_channel
        {
            get { return __pbn__network_channel.GetValueOrDefault(); }
            set { __pbn__network_channel = value; }
        }
        public bool ShouldSerializenetwork_channel() => __pbn__network_channel != null;
        public void Resetnetwork_channel() => __pbn__network_channel = null;
        private uint? __pbn__network_channel;

        [global::ProtoBuf.ProtoMember(6)]
        public AppConfigData app_config { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public uint channel_map
        {
            get { return __pbn__channel_map.GetValueOrDefault(); }
            set { __pbn__channel_map = value; }
        }
        public bool ShouldSerializechannel_map() => __pbn__channel_map != null;
        public void Resetchannel_map() => __pbn__channel_map = null;
        private uint? __pbn__channel_map;

        [global::ProtoBuf.ProtoMember(8)]
        public bool are_keys_set
        {
            get { return __pbn__are_keys_set.GetValueOrDefault(); }
            set { __pbn__are_keys_set = value; }
        }
        public bool ShouldSerializeare_keys_set() => __pbn__are_keys_set != null;
        public void Resetare_keys_set() => __pbn__are_keys_set = null;
        private bool? __pbn__are_keys_set;

        [global::ProtoBuf.ProtoMember(9)]
        public AccessCycleRange current_ac_range { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public AccessCycleRange ac_limits { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public uint max_mtu
        {
            get { return __pbn__max_mtu.GetValueOrDefault(); }
            set { __pbn__max_mtu = value; }
        }
        public bool ShouldSerializemax_mtu() => __pbn__max_mtu != null;
        public void Resetmax_mtu() => __pbn__max_mtu = null;
        private uint? __pbn__max_mtu;

        [global::ProtoBuf.ProtoMember(12)]
        public ChannelRange channel_limits { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public uint hw_magic
        {
            get { return __pbn__hw_magic.GetValueOrDefault(); }
            set { __pbn__hw_magic = value; }
        }
        public bool ShouldSerializehw_magic() => __pbn__hw_magic != null;
        public void Resethw_magic() => __pbn__hw_magic = null;
        private uint? __pbn__hw_magic;

        [global::ProtoBuf.ProtoMember(14)]
        public uint stack_profile
        {
            get { return __pbn__stack_profile.GetValueOrDefault(); }
            set { __pbn__stack_profile = value; }
        }
        public bool ShouldSerializestack_profile() => __pbn__stack_profile != null;
        public void Resetstack_profile() => __pbn__stack_profile = null;
        private uint? __pbn__stack_profile;

        [global::ProtoBuf.ProtoMember(15)]
        public uint app_config_max_size
        {
            get { return __pbn__app_config_max_size.GetValueOrDefault(); }
            set { __pbn__app_config_max_size = value; }
        }
        public bool ShouldSerializeapp_config_max_size() => __pbn__app_config_max_size != null;
        public void Resetapp_config_max_size() => __pbn__app_config_max_size = null;
        private uint? __pbn__app_config_max_size;

        [global::ProtoBuf.ProtoMember(16)]
        public FirmwareVersion firmware_version { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        [global::System.ComponentModel.DefaultValue(OnOffState.On)]
        public OnOffState sink_state
        {
            get { return __pbn__sink_state ?? OnOffState.On; }
            set { __pbn__sink_state = value; }
        }
        public bool ShouldSerializesink_state() => __pbn__sink_state != null;
        public void Resetsink_state() => __pbn__sink_state = null;
        private OnOffState? __pbn__sink_state;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SinkNewConfig //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string sink_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public NodeRole node_role { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint node_address
        {
            get { return __pbn__node_address.GetValueOrDefault(); }
            set { __pbn__node_address = value; }
        }
        public bool ShouldSerializenode_address() => __pbn__node_address != null;
        public void Resetnode_address() => __pbn__node_address = null;
        private uint? __pbn__node_address;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong network_address
        {
            get { return __pbn__network_address.GetValueOrDefault(); }
            set { __pbn__network_address = value; }
        }
        public bool ShouldSerializenetwork_address() => __pbn__network_address != null;
        public void Resetnetwork_address() => __pbn__network_address = null;
        private ulong? __pbn__network_address;

        [global::ProtoBuf.ProtoMember(5)]
        public uint network_channel
        {
            get { return __pbn__network_channel.GetValueOrDefault(); }
            set { __pbn__network_channel = value; }
        }
        public bool ShouldSerializenetwork_channel() => __pbn__network_channel != null;
        public void Resetnetwork_channel() => __pbn__network_channel = null;
        private uint? __pbn__network_channel;

        [global::ProtoBuf.ProtoMember(6)]
        public AppConfigData app_config { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public uint channel_map
        {
            get { return __pbn__channel_map.GetValueOrDefault(); }
            set { __pbn__channel_map = value; }
        }
        public bool ShouldSerializechannel_map() => __pbn__channel_map != null;
        public void Resetchannel_map() => __pbn__channel_map = null;
        private uint? __pbn__channel_map;

        [global::ProtoBuf.ProtoMember(8)]
        public NetworkKeys keys { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public AccessCycleRange current_ac_range { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue(OnOffState.On)]
        public OnOffState sink_state
        {
            get { return __pbn__sink_state ?? OnOffState.On; }
            set { __pbn__sink_state = value; }
        }
        public bool ShouldSerializesink_state() => __pbn__sink_state != null;
        public void Resetsink_state() => __pbn__sink_state = null;
        private OnOffState? __pbn__sink_state;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GatewayInfo //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong current_time_s_epoch { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string gw_model
        {
            get { return __pbn__gw_model ?? ""; }
            set { __pbn__gw_model = value; }
        }
        public bool ShouldSerializegw_model() => __pbn__gw_model != null;
        public void Resetgw_model() => __pbn__gw_model = null;
        private string __pbn__gw_model;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string gw_version
        {
            get { return __pbn__gw_version ?? ""; }
            set { __pbn__gw_version = value; }
        }
        public bool ShouldSerializegw_version() => __pbn__gw_version != null;
        public void Resetgw_version() => __pbn__gw_version = null;
        private string __pbn__gw_version;

        [global::ProtoBuf.ProtoMember(4)]
        public uint implemented_api_version
        {
            get { return __pbn__implemented_api_version.GetValueOrDefault(); }
            set { __pbn__implemented_api_version = value; }
        }
        public bool ShouldSerializeimplemented_api_version() => __pbn__implemented_api_version != null;
        public void Resetimplemented_api_version() => __pbn__implemented_api_version = null;
        private uint? __pbn__implemented_api_version;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StatusEvent //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public EventHeader header { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint version { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public OnOffState state { get; set; } = OnOffState.On;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetConfigsReq //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public RequestHeader header { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetConfigsResp //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ResponseHeader header { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<SinkReadConfig> configs { get; } = new global::System.Collections.Generic.List<SinkReadConfig>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetConfigReq //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public RequestHeader header { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public SinkNewConfig config { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetConfigResp //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ResponseHeader header { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public SinkReadConfig config { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetGwInfoReq //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public RequestHeader header { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetGwInfoResp //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ResponseHeader header { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public GatewayInfo info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WirepasMessage //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public StatusEvent status_event { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public GetConfigsReq get_configs_req { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public GetConfigsResp get_configs_resp { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public SetConfigReq set_config_req { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public SetConfigResp set_config_resp { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public SendPacketReq send_packet_req { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public SendPacketResp send_packet_resp { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public PacketReceivedEvent packet_received_event { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public GetScratchpadStatusReq get_scratchpad_status_req { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public GetScratchpadStatusResp get_scratchpad_status_resp { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public UploadScratchpadReq upload_scratchpad_req { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public UploadScratchpadResp upload_scratchpad_resp { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public ProcessScratchpadReq process_scratchpad_req { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public ProcessScratchpadResp process_scratchpad_resp { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public GetGwInfoReq get_gateway_info_req { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public GetGwInfoResp get_gateway_info_resp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CustomerMessage //: global::ProtoBuf.IExtensible
    {
        //private global::ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string customer_name { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GenericMessage //: global::ProtoBuf.IExtensible
    {
        //private global:Is :ProtoBuf.IExtension __pbn__extensionData;
        //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        //    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public WirepasMessage wirepas { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public CustomerMessage customer { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum FieldType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"FT_DEFAULT")]
        FtDefault = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"FT_CALLBACK")]
        FtCallback = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"FT_POINTER")]
        FtPointer = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"FT_STATIC")]
        FtStatic = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"FT_IGNORE")]
        FtIgnore = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"FT_INLINE")]
        FtInline = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum IntSize
    {
        [global::ProtoBuf.ProtoEnum(Name = @"IS_DEFAULT")]
        IsDefault = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"IS_8")]
        Is8 = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"IS_16")]
        Is16 = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"IS_32")]
        Is32 = 32,
        [global::ProtoBuf.ProtoEnum(Name = @"IS_64")]
        Is64 = 64,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ErrorCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"OK")]
        Ok = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"INTERNAL_ERROR")]
        InternalError = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_SINK_ID")]
        InvalidSinkId = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_ROLE")]
        InvalidRole = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_NETWORK_ADDRESS")]
        InvalidNetworkAddress = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_NETWORK_CHANNEL")]
        InvalidNetworkChannel = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_CHANNEL_MAP")]
        InvalidChannelMap = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_NETWORK_KEYS")]
        InvalidNetworkKeys = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_AC_RANGE")]
        InvalidAcRange = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_SINK_STATE")]
        InvalidSinkState = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_DEST_ADDRESS")]
        InvalidDestAddress = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_DEST_ENDPOINT")]
        InvalidDestEndpoint = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_SRC_ENDPOINT")]
        InvalidSrcEndpoint = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_QOS")]
        InvalidQos = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_DATA_PAYLOAD")]
        InvalidDataPayload = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_SCRATCHPAD")]
        InvalidScratchpad = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_SCRATCHPAD_SIZE")]
        InvalidScratchpadSize = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"INVLAID_SEQUENCE_NUMBER")]
        InvlaidSequenceNumber = 17,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_REBOOT_DELAY")]
        InvalidRebootDelay = 18,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_DIAG_INTERVAL")]
        InvalidDiagInterval = 19,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_APP_CONFIG")]
        InvalidAppConfig = 20,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_PARAM")]
        InvalidParam = 21,
        [global::ProtoBuf.ProtoEnum(Name = @"NO_SCRATCHPAD_PRESENT")]
        NoScratchpadPresent = 22,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCESS_DENIED")]
        AccessDenied = 23,
        [global::ProtoBuf.ProtoEnum(Name = @"REQUEST_NEEDS_SINK_ID")]
        RequestNeedsSinkId = 24,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_MAX_HOP_COUNT")]
        InvalidMaxHopCount = 25,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OnOffState
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ON")]
        On = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"OFF")]
        Off = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ScratchpadType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"BLANK")]
        Blank = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PRESENT")]
        Present = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PROCESS")]
        Process = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ScratchpadStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS")]
        Success = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"NEW")]
        New = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR")]
        Error = 3,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
